// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCif4pw2QljF-eIIR8fx-COiHxm9cbkrls',
    appId: '1:720684311880:web:4028bb36a5748009a87f7d',
    messagingSenderId: '720684311880',
    projectId: 'ml-summative',
    authDomain: 'ml-summative.firebaseapp.com',
    storageBucket: 'ml-summative.firebasestorage.app',
    measurementId: 'G-RJC9B50NXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGTCa9xQDr930KuelB2ZERp585D8KJT88',
    appId: '1:720684311880:android:872524d14b541950a87f7d',
    messagingSenderId: '720684311880',
    projectId: 'ml-summative',
    storageBucket: 'ml-summative.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2X6M2cGtaaRfeAINARU-SUuAMuXW5dVY',
    appId: '1:720684311880:ios:9aec0e04125f2aefa87f7d',
    messagingSenderId: '720684311880',
    projectId: 'ml-summative',
    storageBucket: 'ml-summative.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2X6M2cGtaaRfeAINARU-SUuAMuXW5dVY',
    appId: '1:720684311880:ios:9aec0e04125f2aefa87f7d',
    messagingSenderId: '720684311880',
    projectId: 'ml-summative',
    storageBucket: 'ml-summative.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCif4pw2QljF-eIIR8fx-COiHxm9cbkrls',
    appId: '1:720684311880:web:92a016387660eeaea87f7d',
    messagingSenderId: '720684311880',
    projectId: 'ml-summative',
    authDomain: 'ml-summative.firebaseapp.com',
    storageBucket: 'ml-summative.firebasestorage.app',
    measurementId: 'G-1G89GMCVX0',
  );
}
